// Tips shown on "Mon plan": [category, text]. One per day, the button shows the next one.
export const TIPS = [
  ['Prospection', 'Passe entre 14 h et 16 h : le rush du midi est fini, le patron a le temps de regarder ton téléphone.'],
  ['Prospection', 'Commence par les commerces qui ont une page Instagram active : ils savent déjà que la visibilité compte.'],
  ['Prospection', 'Fais une rue entière d’un coup. Dix commerces à 50 mètres les uns des autres, c’est une heure bien remplie.'],
  ['Prospection', 'Évite le samedi et les veilles de fête pour les boulangeries et les restos : reviens le mardi.'],
  ['Pitch', 'Ouvre avec la maquette, pas avec un discours : « Je vous ai déjà fait votre site, regardez. » Et tends le téléphone.'],
  ['Pitch', 'Parle de ses clients, pas de technique : « Quand quelqu’un cherche une boulangerie ouverte le dimanche, il tombe sur qui ? »'],
  ['Pitch', 'Montre ses vrais horaires et son adresse sur la maquette : c’est ce qui fait « waouh, c’est déjà le mien ».'],
  ['Pitch', 'Pose une question, puis tais-toi. Le silence fait plus vendre que la troisième phrase.'],
  ['Objections', '« J’ai déjà Facebook. » Réponds : « Parfait, le site le met en avant. Mais Google, lui, montre d’abord les sites. »'],
  ['Objections', '« C’est trop cher. » Ramène au mois : « 400 €, c’est 33 € par mois sur un an. Un client en plus par mois et c’est remboursé. »'],
  ['Objections', '« Je vais réfléchir. » Propose une date : « Je repasse jeudi avec la version finale, ça vous prend 10 minutes. »'],
  ['Objections', '« Mon neveu va me le faire. » Souris : « Top. Si dans un mois il n’est pas en ligne, vous m’appelez ? » Et laisse ta carte.'],
  ['Closing', 'Demande 30 % d’acompte à la signature. Le devis intégré le prévoit déjà.'],
  ['Closing', 'Donne une date de mise en ligne précise : « En ligne vendredi. » Une date, ça rassure plus qu’un prix bas.'],
  ['Closing', 'Propose deux options, pas une : site seul, ou site + mise à jour des horaires pendant un an. Le client choisit, il ne dit pas non.'],
  ['Suivi', 'Relance 48 h après, pas une semaine. Un message court : « Je vous ai mis la maquette de côté, on la met en ligne ? »'],
  ['Suivi', 'Note chaque objection dans ton journal. Au bout de 20 contacts, tu verras revenir les trois mêmes : prépare ta réponse.'],
  ['Suivi', 'Un « non » n’est pas un « jamais ». Repasse dans trois mois avec une maquette mise à jour.'],
  ['Admin', 'Crée ton statut de micro-entrepreneur avant ta première vente : c’est gratuit, en ligne, et ça prend 15 minutes.'],
  ['Admin', 'Mets de côté 20 à 25 % de chaque vente pour les cotisations sociales. Ton vrai revenu, c’est le reste.'],
  ['Admin', 'Envoie la facture le jour même de la mise en ligne. Plus tu attends, plus le paiement traîne.'],
  ['Mental', 'Compte tes contacts, pas tes ventes. Les ventes suivent le nombre de portes poussées.'],
  ['Mental', 'Le premier « oui » est le plus dur. Après, tu as une vraie référence à montrer au commerçant d’à côté.'],
  ['Mental', 'Bloque tes créneaux dans ton agenda comme un job : deux sorties de 2 h par semaine valent mieux qu’« un jour où j’aurai le temps ».'],
  ['Croissance', 'Chaque client connaît dix commerçants. Demande-lui : « Vous connaissez quelqu’un à qui ça servirait ? »'],
  ['Croissance', 'Filme une avant/après : la rue sur la carte, puis le site en ligne. C’est ton meilleur contenu TikTok.'],
  ['Croissance', 'Propose un petit forfait mensuel (mises à jour, photos, horaires). Dix clients à 20 €, c’est 200 € qui tombent chaque mois.'],
];
